#:import Header widgets.header
#:import FooterMenu widgets.footer_menu


<BaseScreen>:
    title: ''

    FloatLayout
        canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle
            pos: self.pos
            size: self.size
        # Label:
        #     text: 'Hello S Media Link!'
        #     color: 0, 0, 0, 1

        Header:
            text: root.title

        FooterMenu:
